import type { Metadata } from "next";
import { Crimson_Pro, Great_Vibes, Luxurious_Script } from "next/font/google";
import "./globals.css";
import Providers from "./providers";
import MainMenu from "@/components/main-menu/main-menu";
import Background from "@/components/background/background";

const crimsonPro = Crimson_Pro({
  subsets: ["latin"],
  weight: ["400", "600", "700"],
  variable: "--font-crimson",
});
const greatVibes = Great_Vibes({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-great-vibes",
});

const luxuriousScript = Luxurious_Script({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-luxurious-script",
});

/*const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});*/

export const metadata: Metadata = {
  title: "Eriwen",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${crimsonPro.variable} ${greatVibes.variable} ${luxuriousScript.variable} antialiased min-h-screen h-[200vh]`}
      >
        <Background />
        <Providers>
          <MainMenu />
          <main className="max-w-3xl mx-auto my-16 px-4 py-4 bg-[#D8C293]">
            {children}
          </main>
        </Providers>
      </body>
    </html>
  );
}
