import type { Metadata } from 'next';
import { Cinzel, Luxurious_Script, EB_Garamond } from 'next/font/google';
import './globals.css';
import Providers from './providers';
import MainMenu from '@/components/main-menu/main-menu';
import Background from '@/components/background/background';
import PaperBackground from '@/components/background/paper';

const ebGaramond = EB_Garamond({
  subsets: ['latin'],
  variable: '--font-eb-garamond',
  weight: ['400', '700'],
  style: ['normal', 'italic'],
});
const cinzel = Cinzel({
  subsets: ['latin'],
  weight: ['400'],
  variable: '--font-cinzel',
});

const luxuriousScript = Luxurious_Script({
  subsets: ['latin'],
  weight: ['400'],
  variable: '--font-luxurious-script',
});

export const metadata: Metadata = {
  title: 'Eriwen',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${ebGaramond.variable} ${cinzel.variable} ${luxuriousScript.variable} antialiased min-h-screen overflow-x-hidden`}
      >
        <Background />
        <Providers>
          <MainMenu />
          <main className="relative max-w-3xl mx-auto my-16 px-4 pt-24 pb-16">
            <PaperBackground />
            {children}
          </main>
        </Providers>
      </body>
    </html>
  );
}
