import type { Metadata } from 'next';
import { Cinzel, Great_Vibes, Metamorphous } from 'next/font/google';
import './globals.css';

import Providers from './providers';

import MainMenu from '@/components/main-menu/main-menu';
import UvodMenu from '@/components/uvod-menu/uvod-menu';

import Background from '@/components/background/background';
import PaperBackground from '@/components/background/paper';

const cinzel = Cinzel({
  subsets: ['latin'],
  weight: ['400'],
  variable: '--font-cinzel',
});

const greatVibes = Great_Vibes({
  subsets: ['latin'],
  weight: ['400'],
  variable: '--font-great-vibes',
});

const metamorphous = Metamorphous({
  subsets: ['latin'],
  weight: ['400'],
  variable: '--font-metamorphous',
});

export const metadata: Metadata = {
  title: 'Eriwen',
  description: 'Generated by create next app',
};
export default function Home() {
  return (
    <html lang="en">
      <body
        className={`${cinzel.variable} ${greatVibes.variable} ${metamorphous.variable} antialiased min-h-screen overflow-x-hidden`}
      >
        <Background />
        <Providers>
          <MainMenu />
          <div className="w-full overflow-hidden">
            <UvodMenu />
            <main className="relative max-w-3xl mx-auto my-16 px-4 pt-16 pb-16">
              <PaperBackground />
              <h1 className="headline">Úvod</h1>
              <blockquote>
                „Každé skutečné dobrodružství vzniká nárazem fantazie na
                skutečnost.“<span>Karel Čapek</span>
              </blockquote>
              <h4>Vítejte na stránkách o světě Eriwen,</h4>
              <p>
                pojmenovaném na počest skupiny mladých nadšenců, kteří začali
                hrát dračí doupě v roce 2005, kdy se začal tvořit fantastický
                svět, ve kterém se pohybovali hrdinové známí pod názvem
                Podskalská družina.
              </p>
              <p>
                Každý z nich si nejspíš vzpomene na Barbara Nardena, čaroděje
                Feenixe, hraničáře Lenyho, zlodějky Mušku a Brunhildu, chodce
                Ronkara, alchymistu Toma a chodkyni Ewran.
              </p>
              <p>
                Po mnoha letech se opět někteří z nich sešli, další se přidali,
                aby prožívali úplně nová dobrodružství v novém světě.
              </p>
              <p>
                A o tomto světě se právě můžete dočíst na těchto stránkách. O
                královstvích a krajích, náboženstvích a jednotlivých bozích, o
                spojencích a nepřátelích, ale především o našich hrdinech a
                dobrodružstvích, která zde prožívají.
              </p>
            </main>
          </div>
        </Providers>
      </body>
    </html>
  );
}
