import type { Metadata } from 'next';
import { Cinzel, Great_Vibes, Metamorphous } from 'next/font/google';
import '../globals.css';
import Providers from '../providers';
import MainMenu from '@/components/main-menu/main-menu';
import Background from '@/components/background/background';
import PaperBackground from '@/components/background/paper';

const cinzel = Cinzel({
  subsets: ['latin'],
  weight: ['400'],
  variable: '--font-cinzel',
});

const greatVibes = Great_Vibes({
  subsets: ['latin'],
  weight: ['400'],
  variable: '--font-great-vibes',
});

const metamorphous = Metamorphous({
  subsets: ['latin'],
  weight: ['400'],
  variable: '--font-metamorphous',
});

export const metadata: Metadata = {
  title: 'Eriwen',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${cinzel.variable} ${greatVibes.variable} ${metamorphous.variable} antialiased min-h-screen overflow-x-hidden`}
      >
        <Background />
        <Providers>
          <MainMenu />
          <div className="w-full overflow-hidden">
            <main className="relative max-w-3xl mx-auto my-36 px-4 pt-16 pb-16">
              <PaperBackground />
              {children}
            </main>
          </div>
        </Providers>
      </body>
    </html>
  );
}
